/**
 * The SRD equipment dataset — weapons, armour and adventuring gear, each
 * carrying its price in copper (`meta.costCp`) and its category.
 *
 * PROMOTED, WITH EVIDENCE. All 180 were ingested to `qa: 'draft'` and stayed
 * there, so the loader refused every one outside dev and a character could look
 * at a shop and never buy a rope. `promoteVerifiable` re-reads each price out of
 * its own equipment-table row and promotes only where the printed price and the
 * recorded copper agree — see `ingest/verify.ts`. A row whose price cannot be
 * recovered stays draft.
 *
 * Committed data (items.draft.json), regenerated by `npm run ingest`.
 */
import { RulesEntitySchema, type RulesEntity } from '@questra/contracts';
import { promoteVerifiable } from '../ingest/verify.js';
import draftRecords from './items.draft.json' with { type: 'json' };

/** As ingested, before promotion — what the pipeline goldens compare against. */
export const INGESTED_ITEMS: RulesEntity[] = (draftRecords as unknown[]).map((r) => RulesEntitySchema.parse(r));

/** The equipment list, with everything provable promoted to `verified`. */
export const ITEMS: RulesEntity[] = promoteVerifiable(INGESTED_ITEMS);

/** The ones that could not be proven and are still dev-only. */
export const UNVERIFIED_ITEMS: RulesEntity[] = ITEMS.filter((i) => i.qa === 'draft');

export function draftItems(): RulesEntity[] {
  return ITEMS;
}
