/**
 * The SRD equipment/item dataset — weapons, armor, and adventuring gear ingested
 * to qa:draft with prices (Brief 01 §7). Contracts leaves `item` meta loose, so
 * each draft carries the price in copper pieces (`meta.costCp`) and category;
 * the loader keeps them dev-only until verified.
 *
 * Committed data (items.draft.json), regenerated by `npm run ingest`.
 */
import { RulesEntitySchema, type RulesEntity } from '@questra/contracts';
import draftRecords from './items.draft.json' with { type: 'json' };

/** The draft items, validated against the schema. */
export const DRAFT_ITEMS: RulesEntity[] = (draftRecords as unknown[]).map((r) => RulesEntitySchema.parse(r));

export function draftItems(): RulesEntity[] {
  return DRAFT_ITEMS;
}
