/**
 * The SRD monster dataset. The verified core is the canonical Goblin Warrior
 * fixture (via slice.ts); the remaining ~324 monsters are ingested to qa:draft —
 * their structured meta validates against the contracts schema, but `plain`,
 * `effects[]`, and fully-structured actions await the rules-lawyer pass, so the
 * loader keeps them dev-only until verified.
 *
 * Draft records are committed data (monsters.draft.json), regenerated by
 * `npm run ingest`; no runtime filesystem I/O, and a golden test re-runs the
 * pipeline to guard against drift.
 */
import { RulesEntitySchema, type RulesEntity } from '@questra/contracts';
import { GOBLIN_WARRIOR } from './slice.js';
import draftRecords from './monsters.draft.json' with { type: 'json' };

/** Ids already verified — excluded from the draft set. */
const VERIFIED_MONSTER_IDS = new Set<string>([GOBLIN_WARRIOR.id]);

/** The draft monsters (everything ingested except the verified core), validated against the schema. */
export const DRAFT_MONSTERS: RulesEntity[] = (draftRecords as unknown[])
  .map((r) => RulesEntitySchema.parse(r))
  .filter((m) => !VERIFIED_MONSTER_IDS.has(m.id));

export function draftMonsters(): RulesEntity[] {
  return DRAFT_MONSTERS;
}
