/**
 * The SRD monster dataset.
 *
 * PROMOTED, WITH EVIDENCE. Every one of these was ingested to `qa: 'draft'` and
 * stayed there, which meant the loader refused them outside dev: a DM pressing
 * "Bring something in" was offered exactly one goblin, with the whole SRD
 * bestiary sitting unreachable in the repo. They are promoted here by
 * `promoteVerifiable`, which re-reads each stat block's armour class, hit points
 * and experience OUT OF ITS OWN `srd_text` and promotes only where the printed
 * rule and the recorded meta agree — see `ingest/verify.ts` for what that does
 * and does not certify. Anything that disagrees stays draft and the loader keeps
 * refusing it.
 *
 * What promotion does NOT claim is that a monster's ACTIONS are encoded. They
 * are prose the DM reads and rules on, exactly as at a table; `effects[]` is
 * empty and honest about it.
 *
 * Draft records are committed data (monsters.draft.json), regenerated by
 * `npm run ingest`; no runtime filesystem I/O, and a golden test re-runs the
 * pipeline to guard against drift.
 */
import { RulesEntitySchema, type RulesEntity } from '@questra/contracts';
import { GOBLIN_WARRIOR } from './slice.js';
import { promoteVerifiable } from '../ingest/verify.js';
import draftRecords from './monsters.draft.json' with { type: 'json' };

/** Ids already carried by the verified core — excluded to avoid a duplicate. */
const VERIFIED_MONSTER_IDS = new Set<string>([GOBLIN_WARRIOR.id]);

/** As ingested, before promotion — the byte-stable pipeline output the goldens compare against. */
export const INGESTED_MONSTERS: RulesEntity[] = (draftRecords as unknown[])
  .map((r) => RulesEntitySchema.parse(r))
  .filter((m) => !VERIFIED_MONSTER_IDS.has(m.id));

/** The bestiary, with everything provable promoted to `verified`. */
export const MONSTERS: RulesEntity[] = promoteVerifiable(INGESTED_MONSTERS);

/** The ones that could not be proven and are still dev-only. */
export const UNVERIFIED_MONSTERS: RulesEntity[] = MONSTERS.filter((m) => m.qa === 'draft');

export function draftMonsters(): RulesEntity[] {
  return MONSTERS;
}
