/**
 * Species / backgrounds / feats — ingested to qa:draft (Brief 01 §2). Contracts
 * leaves these types' meta loose (tightened later per their own briefs), so the
 * drafts carry the verbatim srd_text and an empty meta; the loader keeps them
 * dev-only until verified.
 *
 * Committed data (named.draft.json), regenerated by `npm run ingest`; a golden
 * test re-runs the pipeline to guard against drift.
 */
import { RulesEntitySchema, type RulesEntity } from '@questra/contracts';
import draftRecords from './named.draft.json' with { type: 'json' };

/** The 17 draft species/backgrounds/feats, validated against the schema. */
export const DRAFT_NAMED: RulesEntity[] = (draftRecords as unknown[]).map((r) => RulesEntitySchema.parse(r));

export function draftNamed(): RulesEntity[] {
  return DRAFT_NAMED;
}
