/**
 * SRD reference tables — the XP-per-level advancement track and the encounter
 * XP-budget-per-character ladder (Brief 01 §7). These are lookup tables the
 * Engine and DM tools read, not RulesEntities.
 *
 * Committed data (tables.json), regenerated by `npm run ingest`.
 */
import type { AdvancementRow, EncounterBudgetRow } from '../ingest/tables.js';
import tables from './tables.json' with { type: 'json' };

const T = tables as { advancement: AdvancementRow[]; encounterBudget: EncounterBudgetRow[] };

/** Level → cumulative XP threshold + proficiency bonus (levels 1–20). */
export const ADVANCEMENT: AdvancementRow[] = T.advancement;

/** Party level → {low, moderate, high} encounter XP budget per character (levels 1–20). */
export const ENCOUNTER_BUDGET: EncounterBudgetRow[] = T.encounterBudget;

/** XP threshold to reach a level (1–20). */
export function xpForLevel(level: number): number | undefined {
  return ADVANCEMENT.find((r) => r.level === level)?.xp;
}

/** Encounter XP budget per character for a party level and difficulty. */
export function encounterBudget(level: number, difficulty: 'low' | 'moderate' | 'high'): number | undefined {
  return ENCOUNTER_BUDGET.find((r) => r.level === level)?.[difficulty];
}
